version: '3.8'

services:
  delivery_srl_mongodb:
    image: mongo:latest
    container_name: delivery_srl_mongodb
    command: mongod --replSet rs --port 27017
    expose:
      - 27017
    ports:
      - 27017:27017

  delivery_srl_mongodb_init:
    image: mongo:latest
    container_name: delivery_srl_mongodb_init
    depends_on:
      - delivery_srl_mongodb
    volumes:
      - ./init-replica-set.js:/init-replica-set.js

    command: "bash -c 'sleep 7 && mongosh --host delivery_srl_mongodb --port 27017 /init-replica-set.js'"
